inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false
