language: ruby
rvm:
  - 2.6.5
services:
  - postgresql
jobs:
  include:
    - stage: lint
      before_script:
        - gem install brakeman haml-lint rubocop-rails_config
      script:
        - bin/bundle exec rubocop
        - haml-lint app/views/
        - brakeman
    - stage: test
      script:
        - bin/rails db:setup RAILS_ENV=test
        - RAILS_ENV=test bin/rails test
        - ruby -e "require 'json'; json = JSON.parse(File.read('./coverage/.last_run.json')); abort unless json['result']['covered_percent'] >= 99.0"
